// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZ3duT0unq3xNJ57WF6OcBsJE88rlLrU',
    appId: '1:1010835633796:web:4325c15ad93a4ada9bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    authDomain: 'notfound-1.firebaseapp.com',
    storageBucket: 'notfound-1.appspot.com',
    measurementId: 'G-6R6SH7N34Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw8oTsyWon0sqvgW1MwhuPEOg-LqI8Rrs',
    appId: '1:1010835633796:android:5ab49d1a7b1334359bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    storageBucket: 'notfound-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfWRFxs7Cg6r1shzazIJDTROVeIE9yEU',
    appId: '1:1010835633796:ios:e9f5ff743a12f33d9bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    storageBucket: 'notfound-1.appspot.com',
    iosClientId: '1010835633796-ivn8l06vm3oec7dq8a95vaukne22g37u.apps.googleusercontent.com',
    iosBundleId: 'com.notfound.app.notfound',
  );
}
