// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZ3duT0unq3xNJ57WF6OcBsJE88rlLrU',
    appId: '1:1010835633796:web:eff95fd3a90918999bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    authDomain: 'notfound-1.firebaseapp.com',
    storageBucket: 'notfound-1.appspot.com',
    measurementId: 'G-HEK0HCSH0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw8oTsyWon0sqvgW1MwhuPEOg-LqI8Rrs',
    appId: '1:1010835633796:android:c966e359031198f79bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    storageBucket: 'notfound-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVfWRFxs7Cg6r1shzazIJDTROVeIE9yEU',
    appId: '1:1010835633796:ios:ddca7b494c49bdc09bb4d1',
    messagingSenderId: '1010835633796',
    projectId: 'notfound-1',
    storageBucket: 'notfound-1.appspot.com',
    iosClientId: '1010835633796-hmhmpagbf4h434lplrrfp45i1tcst2ha.apps.googleusercontent.com',
    iosBundleId: 'com.notfoundegypt.app',
  );
}
